app = "jokbonode"
primary_region = "nrt"

[build]
  builder = "heroku/builder:24"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

    [[vm]]
  size = 'shared-cpu-1x'

[http_service]
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 0